### ISSUE TITLE
Kodi 19 Matrix Support?

### ISSUE THREAD

**Issue by putrid1** [tamland/xbmc-addon-nrk#64] opened 2021-02-28 16:18 UTC
```
NRK Nett-TV
Version 4.7.0
```
```
Build: Kodi 19.0 (19.0.0) Git:20210219-f44fdfbf67
Compiled: 2021-02-19
Ubuntu 20.04.2 LTS
```

The add-on is not compatible with this version of Kodi

Edit: May have something to do with Python 3.0?

![image](https://user-images.githubusercontent.com/76736133/109425410-65aad480-79e8-11eb-9368-d47d13e0105b.png)
![image](https://user-images.githubusercontent.com/76736133/109425461-9d198100-79e8-11eb-8262-cb0e824e77bf.png)

**Comment by CaptainTyphoo** [comment] 2021-02-28 16:50
This is a duplicate of #56

**Comment by tamland** [comment] 2021-05-23 15:51
Fint om noen vil bidra..

**Comment by boirello** [comment] 2021-05-29 12:16
Prøvde meg på en rask gjennomgang:

addon.xml (fra linje 7):
```python
    <import addon="xbmc.python" version="3.0.0"/>
    <import addon="script.module.requests" version="2.9.1"/>
    <import addon="script.module.routing" version="0.2.0"/>
```

addon.py (linje 222 - denne er jeg litt usikker på):
```python
        #items = nrktv.search(query.decode('utf-8')) # AttributeError: 'str' object has no attribute 'decode'
        items = nrktv.search(query)
```

nrktv.py (linje 293):
```python
    return list(filter(None, map(_hit_to_series_or_program, response['hits']))) # https://stackoverflow.com/questions/36982858/object-of-type-map-has-no-len-in-python-3
```

subs.py (linje 32):
```python
    with open(filename, 'wb') as f: # skriv bytes i stedet
```

subs.py (linje 53):
```python
    for i in range(0, len(subtitles) - 1): # xrange har blitt til range i py3
```

subs.py (fra linje 68 - sikkert mer elegante måter å gjøre dette på):
```python
        output.write(str(i + 1).encode(encoding='UTF-8'))
        output.write(('\n%s' % _time_to_str(start)).encode(encoding='UTF-8'))
        output.write((' --> %s\n' % _time_to_str(end)).encode(encoding='UTF-8'))
        output.write(text)
        output.write('\n\n'.encode(encoding='UTF-8'))
```

Ikke gjennomgående testet, men det lille jeg testet, fungerte i Kodi 19 (Matrix). Vet dog ikke om dette vil ødelegge avspilling i tidligere versjoner av Kodi.

**Comment by CaptainTyphoo** [comment] 2021-05-29 18:29
I also gave it a try and ended up with the following:

```
diff --git a/addon.py b/addon.py
index a956107..328c8d0 100644
--- a/addon.py
+++ b/addon.py
@@ -126,7 +126,7 @@ def show_season_list(series_id, seasons):
     endOfDirectory(plugin.handle)
 
 def show_episode_list(episodes):
-    episodes = filter(lambda ep: getattr(ep, 'available', True), episodes)
+    episodes = [ep for ep in episodes if getattr(ep, 'available', True)]
     for i, item in enumerate(episodes):
         li = ListItem("%s - %s" % (item.episode, item.title))
         set_common_properties(item, li)
@@ -143,7 +143,7 @@ def show_episode_list(episodes):
 
 
 def show_plug_list(items):
-    items = filter(lambda ep: getattr(ep, 'available', True), items)
+    items = [ep for ep in items if getattr(ep, 'available', True)]
     for i, item in enumerate(items):
         title = item.title
         if item.episode:
@@ -201,7 +201,7 @@ def category(category_id):
     xbmcplugin.addSortMethod(plugin.handle, xbmcplugin.SORT_METHOD_PLAYLIST_ORDER)
     xbmcplugin.addSortMethod(plugin.handle, xbmcplugin.SORT_METHOD_LABEL_IGNORE_FOLDERS)
     items = nrktv.programs(category_id)
-    view(items, urls=map(_to_series_or_program_url, items))
+    view(items, urls=list(map(_to_series_or_program_url, items)))
 
 
 @plugin.route('/browse')
@@ -219,8 +219,8 @@ def search():
     keyboard.doModal()
     query = keyboard.getText()
     if query:
-        items = nrktv.search(query.decode('utf-8'))
-        view(items, urls=map(_to_series_or_program_url, items))
+        items = nrktv.search(query)
+        view(items, urls=list(map(_to_series_or_program_url, items)))
 
 
 @plugin.route('/series/<series_id>')
diff --git a/addon.xml b/addon.xml
index f70486a..35d868e 100644
--- a/addon.xml
+++ b/addon.xml
@@ -4,7 +4,7 @@
        version="4.7.0"
        provider-name="takoi">
   <requires>
-    <import addon="xbmc.python" version="2.1.0"/>
+    <import addon="xbmc.python" version="3.0.0"/>
     <import addon="script.module.requests" version="1.0.4"/>
     <import addon="script.module.routing" version="0.1.0"/>
   </requires>
diff --git a/nrktv.py b/nrktv.py
index a84a7c5..a6a242a 100644
--- a/nrktv.py
+++ b/nrktv.py
@@ -15,7 +15,7 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-from __future__ import unicode_literals
+
 
 import datetime
 import re
@@ -274,7 +274,7 @@ def programs(category_id):
     items = _get('/medium/tv/categories/%s/indexelements' % category_id)
     items = [item for item in items if item.get('title', '').strip() != ''
              and item['hasOndemandRights']]
-    return map(_to_series_or_program, items)
+    return list(map(_to_series_or_program, items))
 
 
 def _hit_to_series_or_program(item):
@@ -290,4 +290,4 @@ def search(query):
     response = _get('/search', '&q=' + query)
     if response['hits'] is None:
         return []
-    return filter(None, map(_hit_to_series_or_program, response['hits']))
+    return [_f for _f in map(_hit_to_series_or_program, response['hits']) if _f]
diff --git a/subs.py b/subs.py
index f636738..05653bd 100644
--- a/subs.py
+++ b/subs.py
@@ -19,18 +19,21 @@ import os
 import re
 import xbmc
 import requests
-from io import BytesIO
+from io import StringIO
 
 
 def get_subtitles(video_id):
-    ttml_sub_url = requests.get("http://psapi-granitt-prod-we.cloudapp.net/mediaelement/%s" % (video_id)).json()["subtitlesUrlPath"]
+    mediaelement_json = requests.get("http://psapi-granitt-prod-we.cloudapp.net/mediaelement/%s" % (video_id)).json()
+    if not mediaelement_json["hasSubtitles"]:
+        return None
+    ttml_sub_url = mediaelement_json["subtitlesUrlPath"]
     html = requests.get(ttml_sub_url).text
     if not html:
         return None
 
     content = _ttml_to_srt(html)
     filename = os.path.join(xbmc.translatePath("special://temp"), 'nor.srt')
-    with open(filename, 'w') as f:
+    with open(filename, 'w' ,encoding='utf8') as f:
         f.write(content)
     return filename
 
@@ -51,12 +54,12 @@ def _ttml_to_srt(ttml):
         subtitles.append((start, end, text))
 
     # fix overlapping
-    for i in xrange(0, len(subtitles) - 1):
+    for i in range(0, len(subtitles) - 1):
         start, end, text = subtitles[i]
         start_next, _, _ = subtitles[i + 1]
         subtitles[i] = (start, min(end, start_next - 1), text)
 
-    output = BytesIO()
+    output = StringIO()
     for i, (start, end, text) in enumerate(subtitles):
         text = text.replace('<span style="italic">', '<i>') \
             .replace('</span>', '</i>') \
@@ -64,7 +67,6 @@ def _ttml_to_srt(ttml):
             .split()
         text = ' '.join(text)
         text = re.sub('<br />\s*', '\n', text)
-        text = text.encode('utf-8')
 
         output.write(str(i + 1))
         output.write('\n%s' % _time_to_str(start))
```

The change in get_subtitles() is not strictly necessary for python3, but I ran into an error related to videos without subtitles so I added a fix.

@boirello 
Regarding the changes in subs.py: I would recommend to switch from BytesIO to StringIO, which avoids having to encode and decode the string.

How did you figure out the versions for the requests and routing addons? I left the versions as they were, which worked, but it's probably not correct.

@tamland 
Is there requirement that the nrk addon should work with python2 and python3?

**Comment by boirello** [comment] 2021-05-31 18:05
@CaptainTyphoo 
Well, I didn't figure anything out. I am not a python-guru at all, I just looked at the viaplay code for an example of how to update the code to support Kodi 19 Matrix:
https://github.com/emilsvennesson/kodi-viaplay

And I saw that some dependencies there were newer than in the NRK-addon, so I thought newer could be better. I never tested the addon with the original versions of requests and routing, so it may not be necessary to update at all.

**Comment by awgaan** [comment] 2021-08-31 19:29
@CaptainTyphoo This looks good to me.

Seems like we'd have to maintain two forks of this addon **if** we want to keep it compatible with both Kodi 18+ and Kodi 17 according to this:
> https://forum.kodi.tv/showthread.php?tid=351745

**Comment by solbu** [comment] 2021-08-31 19:45
> Seems like we'd have to maintain two forks of this addon **if** we want to keep it compatible with both Kodi 18+ and Kodi 17 according to this:
> 
> > https://forum.kodi.tv/showthread.php?tid=351745

If it is not to much trouble, my vote is that we should do this.
There are still kodi 17 installations in several LTS distro releases.

**Comment by CaptainTyphoo** [comment] 2021-09-12 15:40
> @CaptainTyphoo This looks good to me.
> 
> Seems like we'd have to maintain two forks of this addon **if** we want to keep it compatible with both Kodi 18+ and Kodi 17 according to this:
> 
> > https://forum.kodi.tv/showthread.php?tid=351745


I think so too.
I would also propose to bump the version of the python3 branch to 5.x, so we can maintain the 4.x version for Kodi < 19.

**Comment by putrid1** [comment] 2021-11-20 18:23
@CaptainTyphoo 
Kodi 19.3.0
Ubuntu 20.04.3

I'm using your version, and some of the new tv-episodes are throwing me this. Any thoughts?
It seems kind of random, as Episode 5 may throw this error, but 6,7,8 works fine.

`One or more items failed to play. Check the log for more information about this message`

```
2021-11-20 19:12:38.979 T:46290    INFO <general>: initializing python engine.
2021-11-20 19:12:39.817 T:45822    INFO <general>: VideoPlayer::OpenFile: plugin://plugin.video.nrk/play/MUHH41000521
2021-11-20 19:12:40.035 T:46290 WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-11-20 19:12:40.035 T:46290 WARNING <general>: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
2021-11-20 19:12:40.036 T:46290    INFO <general>: CPythonInvoker(12, /home/kodi/.kodi/addons/plugin.video.nrk/main.py): script successfully run
2021-11-20 19:12:40.075 T:45822   ERROR <general>: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://nordond26b-f.akamaihd.net/i/wo/open/ps/mu/muhh41000521/muhh41000521aa/muhh41000521aa_,,.mp4.csmil/master.m3u8
2021-11-20 19:12:40.076 T:46293    INFO <general>: Creating InputStream
2021-11-20 19:12:40.102 T:46293   ERROR <general>: CCurlFile::Open failed with code 404 for http://nordond26b-f.akamaihd.net/i/wo/open/ps/mu/muhh41000521/muhh41000521aa/muhh41000521aa_,,.mp4.csmil/master.m3u8:
                                                   
2021-11-20 19:12:40.102 T:46293    INFO <general>: Creating Demuxer
2021-11-20 19:12:40.104 T:46290    INFO <general>: Python interpreter stopped
2021-11-20 19:12:40.364 T:46293   ERROR <general>: OpenDemuxStream - Error creating demuxer
2021-11-20 19:12:40.364 T:46293    INFO <general>: CVideoPlayer::OnExit()
2021-11-20 19:12:40.373 T:45822    INFO <general>: CVideoPlayer::CloseFile()
2021-11-20 19:12:40.374 T:45822    INFO <general>: VideoPlayer: waiting for threads to exit
2021-11-20 19:12:40.374 T:45822    INFO <general>: VideoPlayer: finished waiting

```

**Comment by CaptainTyphoo** [comment] 2021-11-21 17:05
@putrid1 
Could you please provide the exact steps how to reproduce this error (especially the name of the series you were trying to watch)?
Is it always reproducible?
Did you encounter the error with other series/programs too?

**Comment by putrid1** [comment] 2021-11-21 17:55
@CaptainTyphoo 
This was from Førstegangstjenesten https://tv.nrk.no/serie/foerstegangstjenesten
S02E01
S02E05 (*)
Both of them gave me this error.  
E01-04 was released together last week. And only 01 gave error. 02-04 played just fine

E05-08 was released together this week, and only 05 gave error. 06-08 just fine

I have seen this behavior before on some new episodes/series. But can't recall the exact series

**Comment by aigjermo** [comment] 2021-12-15 21:25
@putrid1 and @CaptainTyphoo, I think I've resolved the issue with Førstegangstjenesten and most other series with #68.

**Comment by CaptainTyphoo** [comment] 2022-01-03 18:48
@tamland Is there anything missing in #66 so that it can be closed?

**Closed** 2022-01-04 20:28 UTC

**Comment by petterreinholdtsen** [comment] 2022-05-17 08:12
Any hope to get the add-on published in the official repository for Matrix?
